services:
  - type: web
    name: bharatvox-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app --worker-class uvicorn.workers.UvicornWorker --timeout 120 --bind 0.0.0.0:8000
    autoDeploy: true
